### PR TITLE
first pass at comparing tier lists

### PR DESCRIPTION
**Pull request by wrmacrae**
Please don't merge this for a number of reasons. But I was playing with a tweak to compare people's tier lists (especially from before release) to the 17lands stats, and wants to get a PR up so I could get feedback from people on it using the vercel preview. Thoughts welcome, but also feel free to ignore.

### CODE REVIEW

**Comment by wrmacrae** [comment]
Screen Shot 2022-01-26 at 4 37 36 PM

**Comment by youssefm** [comment]
@wrmacrae looks like the build failed with a Typescript error

**Comment by wrmacrae** [comment]
thanks, just pushed some type fixes. I was working with dev but now it also builds and starts.

**Comment by wrmacrae** [comment]
Closing this out because I got Vercel set up to preview a PR on my fork (https://github.com/wrmacrae/limited-grades/pull/2) and I'll probably end up moving this to be a completely separated app that just uses the API or something.

**Pull request closed without merging**
